-- Projektindítás modul táblái (PostgreSQL).
-- Flyway esetén nevezd át a meglévő migrációk sorszáma szerint (pl. V42__project_kickoff.sql),
-- Liquibase esetén vedd fel sql changeset-ként.

CREATE TABLE project_kickoff (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key           VARCHAR(50)   NOT NULL,
    name                  VARCHAR(100)  NOT NULL,
    description           VARCHAR(1000),
    project_manager_email VARCHAR(254)  NOT NULL,
    private_channel       BOOLEAN       NOT NULL,
    status                VARCHAR(32)   NOT NULL,
    created_by            VARCHAR(254),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version               BIGINT        NOT NULL,
    CONSTRAINT uk_project_kickoff_key UNIQUE (project_key)
);

CREATE INDEX ix_project_kickoff_status ON project_kickoff (status);
CREATE INDEX ix_project_kickoff_created_at ON project_kickoff (created_at);

CREATE TABLE project_kickoff_member (
    kickoff_id  BIGINT       NOT NULL REFERENCES project_kickoff (id) ON DELETE CASCADE,
    position    INTEGER      NOT NULL,
    email       VARCHAR(254) NOT NULL,
    member_role VARCHAR(32)  NOT NULL,
    PRIMARY KEY (kickoff_id, position)
);

CREATE TABLE project_kickoff_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kickoff_id  BIGINT        NOT NULL REFERENCES project_kickoff (id) ON DELETE CASCADE,
    position    INTEGER,
    step_type   VARCHAR(32)   NOT NULL,
    status      VARCHAR(32)   NOT NULL,
    external_id VARCHAR(255),
    url         VARCHAR(1000),
    message     VARCHAR(4000),
    attempts    INTEGER       NOT NULL,
    started_at  TIMESTAMP(6) WITH TIME ZONE,
    finished_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX ix_project_kickoff_step_kickoff ON project_kickoff_step (kickoff_id);
